export interface Project {
  slug: string;
  client: string;
  title: string;
  description: string;
  tags: string[];
  image: string;
  year: string;
  branche: string;
  aufgabe: string;
  loesung: string;
  ergebnis: string;
  stack: string[];
  testimonial?: {
    text: string;
    name: string;
    role: string;
  };
  liveUrl?: string;
  images: string[];
  stats: { label: string; value: string }[];
}

export const PROJECTS: Project[] = [
  {
    slug: "laasen-perle",
    client: "Bergpension Laasen Perle",
    title: "Bergpension Laasen Perle",
    description: "Kompletter Website-Relaunch für die Bergpension am Laasensteig 1 in Kurort Rathen, Sächsische Schweiz. Zimmer-Galerie, Preise und Lighthouse CI.",
    tags: ["Webdesign", "Next.js 15", "SEO", "Lighthouse CI"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gastgewerbe / Tourismus",
    aufgabe: "Die bestehende Website der Bergpension am Laasensteig 1 in Kurort Rathen war veraltet und nicht mobiloptimiert. Gäste konnten keine Zimmer online buchen.",
    loesung: "Kompletter Relaunch mit Next.js 15 und Tailwind CSS 4. Zimmer-Galerie mit echten Fotos, Preisübersicht, integriertes Buchungssystem und automatisiertes Lighthouse Performance Monitoring.",
    ergebnis: "Lighthouse Score 95+, Ladezeit unter 1 Sekunde, deutlich mehr Anfragen über die Website.",
    stack: ["Next.js 15", "React 19", "Tailwind CSS 4", "Lucide Icons", "Lighthouse CI", "Vercel"],
    liveUrl: "https://www.laasenperle.de",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Lighthouse", value: "95+" }, { label: "Ladezeit", value: "<1s" }, { label: "Ort", value: "Rathen" }, { label: "Kontakt", value: "035021 68821" }],
  },
  {
    slug: "lucram-media",
    client: "Lucram Media GmbH",
    title: "Lucram Media — Agentur-Website",
    description: "Premium-Website mit scroll-basiertem Storytelling, YouTube-Hintergründen und Case Studies für Siemens, Intel, Gönrgy, HAPS und Erkenne Den.",
    tags: ["Branding", "Scroll-Storytelling", "Video", "Case Studies"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Digital Media / Video Production",
    aufgabe: "Lucram Media brauchte eine Website, die ihre Arbeit mit Siemens (SIEYA Gamification), Intel (IEM Dallas & Cologne), HAPS (Kinofilm, 35 Mio. Reach), Gönrgy und Nahim Sky (Erkenne Den) auf Premium-Niveau präsentiert.",
    loesung: "Custom Next.js Website mit eigenen Scroll-Komponenten (StickySection, TiltCard, ZoomImage, YouTubeBackground), Testimonial-Karussell und vollständigen Case Study Detail-Seiten pro Projekt.",
    ergebnis: "5 vollständige Case Studies mit Video-Integration. Immersives Scroll-Erlebnis das die Agentur-Arbeit auf höchstem Niveau zeigt.",
    stack: ["Next.js 16", "React 19", "Tailwind CSS 4", "Custom Scroll Animations", "YouTube API"],
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Case Studies", value: "5" }, { label: "Kunden", value: "Siemens, Intel" }, { label: "Reach", value: "35 Mio." }, { label: "Creator", value: "80+" }],
  },
  {
    slug: "kajamed",
    client: "Kajamed — Die Orthopädietechniker",
    title: "Kajamed Medizintechnik",
    description: "Website für Kajamed — Spezialisten für Kinderorthopädietechnik und Kompressionsversorgung in Zwickau und Chemnitz.",
    tags: ["Webdesign", "Medizintechnik", "Multi-Standort", "SEO"],
    image: "https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Medizintechnik / Orthopädie",
    aufgabe: "Kajamed brauchte eine professionelle Online-Präsenz für ihre Standorte in Zwickau und Chemnitz — mit Fokus auf Kinderorthopädie und Kompressionsversorgung.",
    loesung: "Responsive Website mit Multi-Standort-System, Service-Portfolio (Orthopädietechnik, Rehatechnik, Sanitätsfachhandel, Kinderorthopädie), Team-Seite und Stellenangeboten.",
    ergebnis: "Professionelle Darstellung aller Standorte und Leistungsbereiche. Kununu-Integration für Arbeitgeber-Bewertungen.",
    stack: ["Next.js 15", "React 18", "Tailwind CSS 3", "Lucide Icons"],
    liveUrl: "https://www.kajamed.de",
    images: ["https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standorte", value: "Zwickau, Chemnitz" }, { label: "Services", value: "4 Bereiche" }, { label: "Live", value: "kajamed.de" }, { label: "Stack", value: "Next.js 15" }],
  },
  {
    slug: "sv-raedisch",
    client: "Sachverständigenbüro Rädisch",
    title: "SV Rädisch — Immobiliengutachter",
    description: "Website für Dipl.-Wirtsch.-Ing. Lutz Rädisch — Immobiliensachverständiger mit über 20 Jahren Erfahrung in ganz Sachsen. Gutachten ab 990 €.",
    tags: ["Webdesign", "Lokal SEO", "Gutachter", "Sachsen"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Immobilien / Sachverständiger",
    aufgabe: "Dipl.-Wirtsch.-Ing. Lutz Rädisch brauchte eine seriöse Website für Verkehrswert- und Marktwertgutachten mit lokaler SEO-Sichtbarkeit in Dresden, Leipzig, Chemnitz und Umgebung.",
    loesung: "Statische Website mit Alpine.js und Tailwind CSS. Professionelles Schema-Markup, Preisübersicht (ab 990 €), Expertenvorstellung und Kontaktdaten. Standort: Hauptstraße 52a, 01877 Naundorf.",
    ergebnis: "Sichtbarkeit für lokale Suchbegriffe in ganz Sachsen. Seriöser, vertrauensbildender Auftritt der die 20+ Jahre Erfahrung unterstreicht.",
    stack: ["HTML", "Alpine.js", "Tailwind CSS 3"],
    liveUrl: "https://www.sv-raedisch.de",
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Erfahrung", value: "20+ Jahre" }, { label: "Region", value: "Sachsen" }, { label: "Ab", value: "990 €" }, { label: "Tel.", value: "0172 5632259" }],
  },
  {
    slug: "44studio",
    client: "44Studio",
    title: "44Studio — Creator Management",
    description: "Website für 44Studio aus Berlin — Influencer Management Agentur mit Kunden wie Amazon, Netflix, Samsung und Spotify. Reach, Relevanz, Results.",
    tags: ["Branding", "Creator Economy", "Framer Motion", "Berlin"],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Influencer Management / Social Media",
    aufgabe: "44Studio aus Berlin brauchte eine Agentur-Website, die ihr Creator-Portfolio und Brand-Partnerships mit Amazon, Netflix, Samsung und Spotify wirkungsvoll darstellt.",
    loesung: "Next.js Website mit Framer Motion Animationen, Creator-Talent-Management Showcase, Brand Partnership Marquee und Portfolio-Darstellung. Motto: Reach. Relevance. Results.",
    ergebnis: "Professionelle Agentur-Darstellung mit immersiven Animationen und prominenter Darstellung der Brand-Partner.",
    stack: ["Next.js 16", "React 19", "Framer Motion", "Phosphor Icons", "Tailwind CSS 4"],
    liveUrl: "https://www.44studio.de",
    images: ["https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standort", value: "Berlin" }, { label: "Kunden", value: "Amazon, Netflix" }, { label: "Live", value: "44studio.de" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "memora",
    client: "Memora",
    title: "Memora — Influencer Marketing",
    description: "Website für Memora — #1 Partner für Influencer Marketing mit exklusiven Creator-Kooperationen. Standorte Berlin und München.",
    tags: ["Branding", "Influencer", "Scroll-Galerie", "Berlin & München"],
    image: "https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Influencer Marketing",
    aufgabe: "Memora positioniert sich als #1 Partner für Influencer Marketing mit exklusiven und nicht-exklusiven Creator-Kooperationen in Berlin und München.",
    loesung: "Next.js Website mit horizontaler Scroll-Galerie, Creator-Showcase, Partnership-Präsentationen und Brand-Logos (RedBull, Ford, Marvel, Siemens, HelloFresh).",
    ergebnis: "Überzeugende Darstellung des Creator-Netzwerks mit interaktiver Galerie und modernem Agentur-Auftritt.",
    stack: ["Next.js 16", "React 19", "Phosphor Icons", "Tailwind CSS 4"],
    liveUrl: "https://memora.gg",
    images: ["https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standorte", value: "Berlin, München" }, { label: "Brands", value: "RedBull, Ford" }, { label: "Live", value: "memora.gg" }, { label: "Feature", value: "Scroll-Galerie" }],
  },
  {
    slug: "krell-rolladenbau",
    client: "Krell Rolladenbau GmbH",
    title: "Krell — Meisterbetrieb seit 1929",
    description: "Website für Krell Rolladenbau in Waldenburg — Sonnensegel, Markisen, Rollläden, Terrassendächer und Glasoasen. Meisterbetrieb seit 1929 mit 1.000+ Projekten.",
    tags: ["Webdesign", "Handwerk", "Leaflet Maps", "Portfolio"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Handwerk / Sonnenschutz",
    aufgabe: "Krell Rolladenbau — Meisterbetrieb seit 1929 in Waldenburg, Sachsen — brauchte eine Website für ihre Produkte: Sonnensegel, Markisen, Rollläden, Terrassendächer und Glasoasen.",
    loesung: "Next.js Website mit Leaflet-Kartenintegration, Projektgalerie (13+ Referenzbilder), Partner-Logos (Velux, Weinor, Alukon) und hauseigener Fertigung-Darstellung.",
    ergebnis: "Professionelle Darstellung des 95+ Jahre alten Meisterbetriebs mit 1.000+ abgeschlossenen Projekten und interaktiver Standort-Karte.",
    stack: ["Next.js 16", "React 19", "Leaflet", "Tailwind CSS 4"],
    liveUrl: "https://www.krell-rolladenbau.de",
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Seit", value: "1929" }, { label: "Projekte", value: "1.000+" }, { label: "Ort", value: "Waldenburg" }, { label: "Live", value: "krell-rolladenbau.de" }],
  },
  {
    slug: "vietnam-nam",
    client: "Vietnam Nam",
    title: "Vietnam Nam — Restaurant Chemnitz",
    description: "Zweisprachige Website (DE/VN) für Vietnam Nam — vietnamesisches Restaurant in der Zöllnerstraße 6, Chemnitz. 4,7 Sterne bei 1.507 Google-Bewertungen.",
    tags: ["Webdesign", "Gastronomie", "Zweisprachig", "Nodemailer"],
    image: "https://povlib.b-cdn.net/vietnam-nam/interieur-pflanzen.jpg",
    year: "2025",
    branche: "Gastronomie / Restaurant",
    aufgabe: "Vietnam Nam in der Zöllnerstraße 6, Chemnitz brauchte eine ansprechende Website mit Speisekarte, Reservierung und zweisprachiger Darstellung (Deutsch/Vietnamesisch).",
    loesung: "Next.js Website mit Nodemailer für Kontaktformulare, zweisprachigem Interface (DE/VN), Speisekarten-Integration (Phở Hanoi, Sommerrollen, Wok-Spezialitäten), Öffnungszeiten und Reservierung.",
    ergebnis: "4,7 Sterne bei 1.507 Google-Bewertungen. Professioneller Restaurant-Auftritt mit funktionaler Reservierung. Di–So 11:30–14:30, 17:30–22:30.",
    stack: ["Next.js 16", "React 19", "Nodemailer", "Lucide Icons", "Tailwind CSS 4"],
    liveUrl: "https://vietnam-nam.de",
    images: ["https://povlib.b-cdn.net/vietnam-nam/interieur-pflanzen.jpg"],
    stats: [{ label: "Google", value: "4,7★ (1.507)" }, { label: "Sprachen", value: "DE + VN" }, { label: "Adresse", value: "Zöllnerstr. 6" }, { label: "Live", value: "vietnam-nam.de" }],
  },
  {
    slug: "schmiedelandhaus",
    client: "Schmiedelandhaus Greifendorf",
    title: "Schmiedelandhaus — Restaurant",
    description: "Website für das Schmiedelandhaus in Greifendorf — kreative Küche in einer historischen Schmiede mit 50 Plätzen und Gartenbereich für bis zu 200 Gäste.",
    tags: ["Webdesign", "Gastronomie", "WordPress", "Events"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Gastronomie / Restaurant",
    aufgabe: "Das Schmiedelandhaus in Greifendorf — ein Restaurant in einer historischen Schmiede — brauchte eine Website für Reservierungen, Speisekarte und Event-Buchungen.",
    loesung: "Website mit Speisekarte, Reservierungssystem und Event-Darstellung. Mehrere Gasträume (alte Schmiede mit offenem Herd, Schmiedestube), Gartenbereich und Catering-Service.",
    ergebnis: "Do–Fr 17–22 Uhr, Sa 9–22 Uhr, So 9–20 Uhr. 50 Sitzplätze innen, bis 200 Gäste mit Zelt im Garten. Sushi-Abende und 9-Gänge-Menüs als Highlights.",
    stack: ["WordPress", "HTML", "CSS"],
    liveUrl: "https://schmiedelandhaus.de",
    images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Plätze", value: "50 + Garten" }, { label: "Events", value: "bis 200 Gäste" }, { label: "Ort", value: "Greifendorf" }, { label: "Live", value: "schmiedelandhaus.de" }],
  },
  {
    slug: "vision-media",
    client: "Vision Media",
    title: "Vision Media — Videoproduktion",
    description: "Portfolio-Website für Vision Media — Cinematic Video Content, High-End Photography und Social Media Content Production.",
    tags: ["Webdesign", "Portfolio", "Video", "Kreativagentur"],
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Videoproduktion / Kreativagentur",
    aufgabe: "Vision Media brauchte eine Portfolio-Website, die ihre cinematischen Produktionen und fotografischen Arbeiten wirkungsvoll in Szene setzt.",
    loesung: "Visuelle Portfolio-Website mit Video-Reels, Manifesto-Sektion, Projekt-Statistiken und immersiver Bildsprache.",
    ergebnis: "Kraftvolle Darstellung des kreativen Portfolios mit Video-Integration und professioneller Positionierung.",
    stack: ["Next.js 16", "React 19", "Lucide Icons", "Tailwind CSS 4"],
    liveUrl: "https://visionmedia.de",
    images: ["https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Portfolio" }, { label: "Content", value: "Video + Foto" }, { label: "Live", value: "visionmedia.de" }, { label: "Design", value: "Cinematic" }],
  },
  {
    slug: "glasbison",
    client: "Glass Bison",
    title: "Glass Bison — Künstler-Management",
    description: "Website für Glass Bison — Künstler-Management mit strategischem Ansatz und kreativer Vision für Musiker und Entertainer.",
    tags: ["Webdesign", "Branding", "Musik", "Framer Motion"],
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Musik & Entertainment",
    aufgabe: "Glass Bison brauchte eine Website, die ihr Künstler-Management professionell präsentiert — strategisches Management trifft kreative Vision.",
    loesung: "Moderne Portfolio-Website mit Framer Motion Animationen, Artist-Showcase und Management-Darstellung.",
    ergebnis: "Professioneller Online-Auftritt mit immersivem Design und klarer Positionierung im Musik-Management.",
    stack: ["Next.js 16", "React 19", "Framer Motion", "Lucide Icons", "Tailwind CSS 4"],
    liveUrl: "https://www.glassbison.com",
    images: ["https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Musik" }, { label: "Typ", value: "Management" }, { label: "Live", value: "glassbison.com" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "salty-beach",
    client: "Salty Beach",
    title: "Salty Beach — Luxury Salt Lounge",
    description: "Premium-Website für eine Design-Salzlounge mit Halotherapie — zweisprachig (Englisch/Arabisch), Lenis Smooth Scrolling und Framer Motion.",
    tags: ["Luxury", "Wellness", "Zweisprachig EN/AR", "Lenis"],
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Wellness / Luxury",
    aufgabe: "Salty Beach brauchte eine Premium-Website für ihre exklusive Salzlounge mit Halotherapie-Erlebnis — zweisprachig für ein internationales Publikum (Englisch/Arabisch).",
    loesung: "Luxury-Website mit Lenis Smooth Scrolling, Framer Motion Animationen, zweisprachigem Content (EN/AR), Gallery-Sektionen und immersivem Design.",
    ergebnis: "Hochwertiger Online-Auftritt der das Premium-Salzlounge-Erlebnis digital transportiert.",
    stack: ["Next.js 16", "React 19", "Framer Motion", "Lenis", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Sprachen", value: "EN + AR" }, { label: "Scrolling", value: "Lenis" }, { label: "Design", value: "Luxury" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "regalflaechendesign",
    client: "Regalflächendesign",
    title: "Regalflächendesign — Laden- & Messebau",
    description: "Website für Regalflächendesign in Chemnitz — Montagen im Laden- und Messebau, Regalflächenbau und Regalprüfung. Tel. 0371 234794 10.",
    tags: ["Webdesign", "Handwerk", "Vorher/Nachher", "Jobs"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Laden- und Messebau",
    aufgabe: "Regalflächendesign in Chemnitz brauchte eine professionelle Website für ihre Montage-Leistungen im Laden- und Messebau mit Vorher/Nachher-Referenzen.",
    loesung: "Responsive Website mit Vorher/Nachher-Slidern für Referenzprojekte, Leistungsübersicht, Stellenangeboten und Kontaktformular.",
    ergebnis: "Professionelle Online-Präsenz mit visuellen Projektbeispielen und direkter Kontaktmöglichkeit unter 0371 234794 10.",
    stack: ["Next.js 15", "React 19", "Clsx", "Lucide Icons", "Tailwind CSS 3"],
    images: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standort", value: "Chemnitz" }, { label: "Feature", value: "Vorher/Nachher" }, { label: "Tel.", value: "0371 234794 10" }, { label: "Stack", value: "Next.js 15" }],
  },
  {
    slug: "in-tec",
    client: "In-Tec",
    title: "In-Tec — Bauunternehmen",
    description: "Website für In-Tec — Bauunternehmen mit Vorher/Nachher-Slidern, Social Proof und professioneller Leistungsdarstellung.",
    tags: ["Webdesign", "Bau", "Vorher/Nachher", "SEO"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Bau / Handwerk",
    aufgabe: "In-Tec brauchte eine moderne Website, die ihr Leistungsspektrum im Bauwesen professionell darstellt und Vertrauen schafft.",
    loesung: "Next.js Website mit Vorher/Nachher-Slider für Bauprojekte, Service-Sektionen, Social Proof Elementen und Kontaktformular.",
    ergebnis: "Überzeugende Darstellung der Bauleistungen mit visuellen Projektreferenzen und direktem Kundenkontakt.",
    stack: ["Next.js 16", "React 19", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Bau" }, { label: "Feature", value: "Slider" }, { label: "Stack", value: "Next.js 16" }, { label: "Design", value: "Modern" }],
  },
  {
    slug: "trendbau",
    client: "Trendbau Wendlandt",
    title: "Trendbau — Bauunternehmen",
    description: "Website für Trendbau Wendlandt — Bauunternehmen mit Projektgalerie, Vorher/Nachher-Vergleichen und Leistungsübersicht.",
    tags: ["Webdesign", "Bau", "Geist UI", "Portfolio"],
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Bau / Handwerk",
    aufgabe: "Trendbau Wendlandt brauchte eine professionelle Website, die ihre Bauprojekte — u.a. für Douglas und Thomann — überzeugend präsentiert.",
    loesung: "Moderne Website mit Geist UI Typography, Vorher/Nachher-Slidern für Projekte wie Douglas-Umbau und Thomann-Showroom, Service-Showcase und Kontaktformularen.",
    ergebnis: "Professioneller Webauftritt mit visueller Darstellung realer Projekte (Douglas, Thomann, Cube).",
    stack: ["Next.js 16", "React 19", "Geist UI", "Lucide Icons", "Tailwind CSS 4"],
    liveUrl: "https://trendbau-wendlandt.de",
    images: ["https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Kunden", value: "Douglas, Thomann" }, { label: "Font", value: "Geist UI" }, { label: "Live", value: "trendbau-wendlandt.de" }, { label: "Feature", value: "Slider" }],
  },
  {
    slug: "bedag",
    client: "BeDaG",
    title: "BeDaG — Dachdeckerbetrieb",
    description: "Website für BeDaG — Dachdeckerbetrieb mit Service-Darstellung, Kundenstimmen und Blog für Expertise-Positionierung.",
    tags: ["Webdesign", "Handwerk", "Blog", "Framer Motion"],
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Handwerk / Dachdecker",
    aufgabe: "BeDaG brauchte eine moderne Website mit Leistungsdarstellung, Kundenstimmen und einem Blog für Expertise-Positionierung.",
    loesung: "Next.js Website mit Framer Motion Animationen, Service-Karten, Testimonial-Sektion und integriertem Blog.",
    ergebnis: "Moderner Webauftritt mit Kundenstimmen, Blog-Content und klarer Service-Darstellung.",
    stack: ["Next.js 16", "React 19", "Framer Motion", "Tailwind CSS 4"],
    liveUrl: "https://bedag-dach.de",
    images: ["https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Dachdecker" }, { label: "Feature", value: "Blog" }, { label: "Live", value: "bedag-dach.de" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "gegenschlag24",
    client: "Gegenschlag 24",
    title: "GS24 — Fußball-Team",
    description: "Website für Gegenschlag 24 — Fußball-Team mit Spielplan, Kader-Übersicht, News und Sponsoren-Darstellung.",
    tags: ["Webdesign", "Sport", "Team", "Geist UI"],
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Sport / Fußball",
    aufgabe: "Das Fußball-Team Gegenschlag 24 brauchte eine zentrale Website mit Spielplan, Kader, News und Sponsoren-Darstellung.",
    loesung: "Moderne Team-Website mit Geist UI Typography, Spielplan-System, Kader-Übersicht, News-Sektion und Sponsor-Showcase.",
    ergebnis: "Zentrale Anlaufstelle für Fans und Sponsoren mit allen Team-Informationen auf einen Blick.",
    stack: ["Next.js 16", "React 19", "Geist UI", "Tailwind CSS 4"],
    liveUrl: "https://gegenschlag24.de",
    images: ["https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Team-Website" }, { label: "Features", value: "Spielplan, Kader" }, { label: "Live", value: "gegenschlag24.de" }, { label: "Content", value: "News" }],
  },
  {
    slug: "plauderbot",
    client: "Plauderbot",
    title: "Plauderbot — KI-Chatbot",
    description: "Landing Page für Plauderbot — unser eigenes Produkt: KI-gestützter Chatbot für Websites. Feature-Highlights, Pricing und Produkt-Showcase.",
    tags: ["KI", "SaaS", "Eigenes Produkt", "Landing Page"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Software / KI",
    aufgabe: "Plauderbot ist unser eigenes Produkt — ein KI-Chatbot für Websites. Die Landing Page präsentiert Features, Vorteile und Preise.",
    loesung: "Produkt-Landing-Page mit Feature-Highlights, Preis-Darstellung und klarem Call-to-Action.",
    ergebnis: "Überzeugende Produktseite, die Plauderbot als professionelle KI-Lösung für Unternehmen positioniert.",
    stack: ["Next.js 15", "React 18", "Tailwind CSS 3", "Lucide Icons"],
    liveUrl: "https://plauder-bot.de",
    images: ["https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Eigenes Produkt" }, { label: "Tech", value: "KI / AI" }, { label: "Live", value: "plauder-bot.de" }, { label: "Status", value: "Live" }],
  },
  {
    slug: "defuse-digital",
    client: "defuse. digital",
    title: "defuse. — Eigene Agentur-Website",
    description: "Unsere eigene Website — scroll-basiertes Storytelling, 18+ Case Studies, 9-Schritte Projekt-Konfigurator und vollständige SEO-Infrastruktur.",
    tags: ["Webdesign", "SEO", "Konfigurator", "Eigenes Projekt"],
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Digitalagentur",
    aufgabe: "Unsere eigene Website sollte zeigen, was wir können — Premium-Design, SEO-Infrastruktur, Custom-Komponenten und 9-Schritte Projekt-Konfigurator.",
    loesung: "Next.js 16 Website mit Custom Scroll-Komponenten (StickySection, TiltCard, Reveal, CountUp), JSON-LD, programmatischer Sitemap, robots.txt und vollständigem Konfigurator.",
    ergebnis: "Eat-your-own-dogfood: Die Website demonstriert live alles, was wir für Kunden bauen.",
    stack: ["Next.js 16", "React 19", "Tailwind CSS 4", "Lucide Icons", "TypeScript", "Vercel"],
    liveUrl: "https://defuse.digital",
    images: ["https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Projekte", value: "18+" }, { label: "Konfigurator", value: "9 Steps" }, { label: "SEO", value: "JSON-LD" }, { label: "Live", value: "defuse.digital" }],
  },
];
