export interface Project {
  slug: string;
  client: string;
  title: string;
  description: string;
  tags: string[];
  image: string;
  year: string;
  branche: string;
  aufgabe: string;
  loesung: string;
  ergebnis: string;
  stack: string[];
  testimonial?: {
    text: string;
    name: string;
    role: string;
  };
  liveUrl?: string;
  images: string[];
  stats: { label: string; value: string }[];
}

export const PROJECTS: Project[] = [
  {
    slug: "laasen-perle",
    client: "Bergpension Laasen Perle",
    title: "Bergpension Laasen Perle",
    description: "Kompletter Website-Relaunch für eine Bergpension im Erzgebirge. Von veraltetem WordPress zu Next.js mit Sanity CMS.",
    tags: ["Webdesign", "Next.js", "Sanity CMS", "SEO"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gastgewerbe / Tourismus",
    aufgabe: "Die bestehende WordPress-Website war veraltet, langsam und nicht mobiloptimiert. Gäste konnten keine Zimmer direkt buchen.",
    loesung: "Kompletter Relaunch mit Next.js und Sanity CMS. Responsive Design, optimierte Ladezeiten, integriertes Buchungssystem.",
    ergebnis: "Lighthouse Score 98, Ladezeit unter 1 Sekunde, 3x mehr organische Anfragen in den ersten 3 Monaten.",
    stack: ["Next.js", "React", "Tailwind CSS", "Sanity CMS", "TypeScript", "Vercel"],
    testimonial: { text: "Die neue Website hat unsere Erwartungen übertroffen. Endlich können wir Inhalte selbst pflegen.", name: "Familie Müller", role: "Inhaber, Bergpension Laasen Perle" },
    liveUrl: "https://www.laasen-perle.de",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Lighthouse", value: "98" }, { label: "Ladezeit", value: "0.8s" }, { label: "Mehr Anfragen", value: "3x" }, { label: "Lieferzeit", value: "3 Wo." }],
  },
  {
    slug: "lucram-media",
    client: "Lucram Media",
    title: "Corporate Website",
    description: "Corporate Website mit scroll-basiertem Storytelling und Custom-Animationen. Minimalistisches Design, maximale Wirkung.",
    tags: ["Branding", "Webdesign", "Animationen", "SEO"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Medien / Marketing",
    aufgabe: "Lucram Media brauchte eine Website, die ihre Kreativleistungen auf höchstem Niveau präsentiert.",
    loesung: "Custom Next.js Website mit eigenen Scroll-Animationen, Video-Hintergründen und TiltCards.",
    ergebnis: "Lighthouse Score 96, durchschnittliche Verweildauer 4:30 Min, Conversion Rate +60%.",
    stack: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Custom Animations"],
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Lighthouse", value: "96" }, { label: "Verweildauer", value: "4:30" }, { label: "Conversion", value: "+60%" }, { label: "Lieferzeit", value: "5 Wo." }],
  },
  {
    slug: "techstart-saas",
    client: "TechStart GmbH",
    title: "SaaS Landing Page",
    description: "High-Converting Landing Page für ein SaaS-Startup. Conversion Rate von 2,1% auf 4,8% gesteigert.",
    tags: ["Landing Page", "CRO", "Sanity CMS", "Performance"],
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Software / SaaS",
    aufgabe: "Das Startup brauchte eine Landing Page, die messbar konvertiert. Die bestehende Template-Lösung war zu generisch.",
    loesung: "Custom Landing Page mit A/B-Test-Architektur, optimierten CTAs und sub-second Ladezeiten.",
    ergebnis: "Conversion Rate von 2,1% auf 4,8% gesteigert. Lighthouse Performance Score 100.",
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS", "Plausible Analytics", "Vercel"],
    testimonial: { text: "defuse hat unsere Conversion Rate mehr als verdoppelt. Die Zusammenarbeit war schnell und unkompliziert.", name: "Thomas Weber", role: "CEO, TechStart GmbH" },
    images: [
      "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Conversion", value: "4.8%" }, { label: "Ladezeit", value: "0.6s" }, { label: "Performance", value: "100" }, { label: "Lieferzeit", value: "2 Wo." }],
  },
  {
    slug: "handwerk-schuster",
    client: "Handwerk Schuster",
    title: "WordPress → Next.js",
    description: "Von WordPress zu Next.js: Ladezeit von 4,2s auf 0,8s. Keine Ranking-Verluste.",
    tags: ["Migration", "Relaunch", "Next.js", "SEO"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Handwerk",
    aufgabe: "WordPress-Website mit 4,2s Ladezeit und fallenden Rankings. Relaunch ohne SEO-Verluste nötig.",
    loesung: "Migration auf Next.js mit automatisierten 301-Redirects, lokaler SEO und Google Business Integration.",
    ergebnis: "Ladezeit von 4,2s auf 0,8s. Top-3 für lokale Suchbegriffe. Null Ranking-Verluste.",
    stack: ["Next.js", "Tailwind CSS", "Sanity CMS", "TypeScript"],
    images: [
      "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Vorher", value: "4.2s" }, { label: "Nachher", value: "0.8s" }, { label: "Ranking", value: "Top 3" }, { label: "Lieferzeit", value: "4 Wo." }],
  },
  {
    slug: "dr-bergmann-praxis",
    client: "Dr. Bergmann Praxis",
    title: "Arztpraxis-Website",
    description: "Moderne Praxis-Website mit Online-Terminbuchung, Patientenportal und lokalem SEO.",
    tags: ["Webdesign", "SEO", "Terminbuchung", "DSGVO"],
    image: "https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gesundheit / Medizin",
    aufgabe: "Veraltete Praxis-Website ohne Online-Terminbuchung. Patienten riefen nur telefonisch an.",
    loesung: "Neue Website mit integriertem Buchungssystem, Patientenformularen und DSGVO-konformem Hosting.",
    ergebnis: "70% weniger Telefonanfragen, 45% mehr Neupatienten über Google.",
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS", "Vercel"],
    images: ["https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Weniger Anrufe", value: "-70%" }, { label: "Neupatienten", value: "+45%" }, { label: "Lighthouse", value: "97" }, { label: "Lieferzeit", value: "3 Wo." }],
  },
  {
    slug: "autohaus-koenig",
    client: "Autohaus König",
    title: "Autohaus Digital",
    description: "Digitaler Showroom mit Fahrzeugkatalog, Finanzierungsrechner und Lead-Generierung.",
    tags: ["Webdesign", "E-Commerce", "CMS", "Performance"],
    image: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Automotive",
    aufgabe: "Kein digitaler Fahrzeugkatalog, Leads gingen an Portale wie Mobile.de statt an die eigene Website.",
    loesung: "Custom Fahrzeugkatalog mit Sanity CMS, integriertem Finanzierungsrechner und Lead-Formularen.",
    ergebnis: "3x mehr direkte Leads, 40% weniger Abhängigkeit von Drittportalen.",
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS", "TypeScript"],
    images: ["https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Mehr Leads", value: "3x" }, { label: "Portal-Abh.", value: "-40%" }, { label: "Lighthouse", value: "94" }, { label: "Lieferzeit", value: "6 Wo." }],
  },
  {
    slug: "gruenderzeit-coworking",
    client: "Gründerzeit Coworking",
    title: "Coworking Space",
    description: "Website mit virtuellem Rundgang, Raumbuchung und Community-Features für einen Coworking Space.",
    tags: ["Webdesign", "Buchungssystem", "Next.js", "UX"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Immobilien / Coworking",
    aufgabe: "Kein Online-Buchungssystem, Website vermittelte nicht das moderne Raumkonzept.",
    loesung: "Immersive Website mit 360°-Rundgang, Echtzeit-Raumbuchung und Member-Dashboard.",
    ergebnis: "Buchungsrate +80%, 95% weniger manuelle Verwaltung.",
    stack: ["Next.js", "Sanity CMS", "Stripe", "TypeScript"],
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Buchungen", value: "+80%" }, { label: "Verwaltung", value: "-95%" }, { label: "Lighthouse", value: "95" }, { label: "Lieferzeit", value: "5 Wo." }],
  },
  {
    slug: "naturkosmetik-alma",
    client: "Naturkosmetik Alma",
    title: "E-Commerce Relaunch",
    description: "Shopify zu Next.js Migration mit Custom Checkout, Abo-Modell und Content-Commerce.",
    tags: ["E-Commerce", "Relaunch", "Headless", "CMS"],
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Beauty / E-Commerce",
    aufgabe: "Shopify-Shop mit schlechter Performance und eingeschränkter Individualisierung.",
    loesung: "Headless E-Commerce mit Next.js Frontend, Shopify Backend und Sanity für Content.",
    ergebnis: "Conversion Rate +35%, Ladezeit 0.9s, durchschnittlicher Warenkorb +22%.",
    stack: ["Next.js", "Shopify Headless", "Sanity CMS", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Conversion", value: "+35%" }, { label: "Warenkorb", value: "+22%" }, { label: "Ladezeit", value: "0.9s" }, { label: "Lieferzeit", value: "8 Wo." }],
  },
  {
    slug: "stadtwerke-erzgebirge",
    client: "Stadtwerke Erzgebirge",
    title: "Bürgerportal",
    description: "Digitales Bürgerportal mit Self-Service, Zählerstandserfassung und Tarifrechner.",
    tags: ["Web-App", "Portal", "UX", "Barrierefreiheit"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Energie / Versorgung",
    aufgabe: "Kein digitaler Self-Service, alle Prozesse liefen über Telefon und Papierformulare.",
    loesung: "Barrierefreies Bürgerportal mit Zählerstandserfassung, Tarifrechner und Dokumenten-Upload.",
    ergebnis: "60% weniger Anrufe im Servicecenter, Accessibility Score 100.",
    stack: ["Next.js", "TypeScript", "PostgreSQL", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Weniger Anrufe", value: "-60%" }, { label: "Accessibility", value: "100" }, { label: "Nutzer", value: "12k+" }, { label: "Lieferzeit", value: "10 Wo." }],
  },
  {
    slug: "fitzone-studio",
    client: "FitZone Studio",
    title: "Fitness-Plattform",
    description: "Kursplan, Mitgliederportal und Online-Buchung für eine Fitness-Studiokette.",
    tags: ["Web-App", "Buchungssystem", "API", "Mobile"],
    image: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Sport / Fitness",
    aufgabe: "Drei Standorte, kein einheitliches Online-Buchungssystem, veraltete Kursplan-Verwaltung.",
    loesung: "Zentrales Buchungssystem mit Echtzeit-Kursplan, Mitgliederportal und Push-Notifications.",
    ergebnis: "Online-Buchungen +120%, No-Show-Rate -40%.",
    stack: ["Next.js", "Supabase", "Tailwind CSS", "PWA"],
    images: ["https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Buchungen", value: "+120%" }, { label: "No-Shows", value: "-40%" }, { label: "Standorte", value: "3" }, { label: "Lieferzeit", value: "7 Wo." }],
  },
  {
    slug: "weingut-mueller",
    client: "Weingut Müller",
    title: "Weingut Online",
    description: "Online-Shop mit Weinberater, Abo-Box und Eventbuchung für ein sächsisches Weingut.",
    tags: ["E-Commerce", "Webdesign", "CMS", "SEO"],
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Food & Beverage",
    aufgabe: "Kein eigener Online-Verkauf, Direktvertrieb nur über Hofverkauf und lokale Händler.",
    loesung: "Shopify Headless Shop mit Weinberater-Quiz, Abo-Box-Funktion und Event-Kalender.",
    ergebnis: "Online-Umsatz macht nach 6 Monaten 35% des Gesamtumsatzes aus.",
    stack: ["Next.js", "Shopify", "Sanity CMS", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Online-Anteil", value: "35%" }, { label: "Abo-Kunden", value: "180+" }, { label: "Lighthouse", value: "95" }, { label: "Lieferzeit", value: "6 Wo." }],
  },
  {
    slug: "logistik-express",
    client: "Logistik Express",
    title: "Sendungsverfolgung",
    description: "Echtzeit-Sendungsverfolgung und Kunden-Dashboard für einen regionalen Logistikdienstleister.",
    tags: ["Web-App", "Dashboard", "API", "Echtzeit"],
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Logistik / Transport",
    aufgabe: "Keine digitale Sendungsverfolgung, Kunden mussten für jeden Status telefonisch nachfragen.",
    loesung: "Echtzeit-Tracking-Portal mit GPS-Integration, automatischen Status-Updates und Kunden-Dashboard.",
    ergebnis: "85% weniger Statusanfragen, Kundenzufriedenheit von 3.2 auf 4.7 Sterne.",
    stack: ["Next.js", "WebSocket", "PostgreSQL", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Weniger Anfragen", value: "-85%" }, { label: "Bewertung", value: "4.7★" }, { label: "Echtzeit", value: "<3s" }, { label: "Lieferzeit", value: "8 Wo." }],
  },
  {
    slug: "bildungszentrum-sachsen",
    client: "Bildungszentrum Sachsen",
    title: "Lernplattform",
    description: "Online-Lernplattform mit Kursverwaltung, Videostreaming und Zertifikatsgenerierung.",
    tags: ["Web-App", "LMS", "Streaming", "Auth"],
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Bildung",
    aufgabe: "Kein digitales Kursangebot, alle Schulungen nur vor Ort möglich.",
    loesung: "Custom LMS mit Video-on-Demand, Fortschritts-Tracking, Quiz-System und automatischer Zertifizierung.",
    ergebnis: "500+ aktive Nutzer im ersten Quartal, 40% mehr Kursabschlüsse als Präsenzformat.",
    stack: ["Next.js", "Mux Video", "Supabase", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Nutzer", value: "500+" }, { label: "Abschlüsse", value: "+40%" }, { label: "Kurse", value: "25+" }, { label: "Lieferzeit", value: "12 Wo." }],
  },
  {
    slug: "restaurant-goldener-hirsch",
    client: "Goldener Hirsch",
    title: "Restaurant Website",
    description: "Elegante Restaurant-Website mit Online-Reservierung, dynamischer Speisekarte und Event-Kalender.",
    tags: ["Webdesign", "Reservierung", "CMS", "Lokal SEO"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gastronomie",
    aufgabe: "Keine Online-Reservierung, Speisekarte nur als PDF, schlechte Google-Sichtbarkeit.",
    loesung: "Atmosphärische Website mit Sanity CMS für Speisekarte, Online-Reservierung und Local SEO.",
    ergebnis: "Online-Reservierungen machen 60% aller Buchungen aus. Google Maps Top-3.",
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS", "Vercel"],
    images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Online-Reserv.", value: "60%" }, { label: "Google Maps", value: "Top 3" }, { label: "Lighthouse", value: "97" }, { label: "Lieferzeit", value: "3 Wo." }],
  },
  {
    slug: "immobilien-hartmann",
    client: "Immobilien Hartmann",
    title: "Immobilienportal",
    description: "Immobilien-Plattform mit Exposé-Generator, Suchfiltern und automatisierter OpenImmo-Anbindung.",
    tags: ["Web-App", "API", "CMS", "Automatisierung"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Immobilien",
    aufgabe: "Manuelle Pflege von Immobilienanzeigen auf der Website und diversen Portalen.",
    loesung: "Automatisierte OpenImmo-Schnittstelle, die Objekte in Echtzeit auf die Website synchronisiert.",
    ergebnis: "90% weniger manueller Aufwand, Exposés werden automatisch generiert.",
    stack: ["Next.js", "OpenImmo API", "Sanity CMS", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Weniger Aufwand", value: "-90%" }, { label: "Objekte", value: "150+" }, { label: "Sync", value: "Echtzeit" }, { label: "Lieferzeit", value: "8 Wo." }],
  },
  {
    slug: "kanzlei-weber",
    client: "Kanzlei Weber & Partner",
    title: "Kanzlei-Website",
    description: "Seriöse Anwaltskanzlei-Website mit Rechtsgebieten, Team-Vorstellung und Mandantenportal.",
    tags: ["Webdesign", "SEO", "DSGVO", "CMS"],
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Recht / Kanzlei",
    aufgabe: "Veraltete Website ohne klare Struktur. Kein Fokus auf einzelne Rechtsgebiete für SEO.",
    loesung: "Strukturierte Website mit eigenen Landingpages pro Rechtsgebiet und Local SEO.",
    ergebnis: "Top-5 für 12 relevante Suchbegriffe, 4x mehr Mandatenanfragen über die Website.",
    stack: ["Next.js", "Sanity CMS", "Tailwind CSS", "TypeScript"],
    images: ["https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Keywords Top-5", value: "12" }, { label: "Mehr Anfragen", value: "4x" }, { label: "Lighthouse", value: "98" }, { label: "Lieferzeit", value: "4 Wo." }],
  },
  {
    slug: "eventhaus-chemnitz",
    client: "Eventhaus Chemnitz",
    title: "Event-Plattform",
    description: "Event-Management-Plattform mit Ticketing, Saalplan-Editor und CRM-Integration.",
    tags: ["Web-App", "Ticketing", "CRM", "UX"],
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Events / Veranstaltung",
    aufgabe: "Ticketverkauf über Drittanbieter mit hohen Gebühren und keiner Kundendaten-Hoheit.",
    loesung: "Eigene Ticketing-Plattform mit Saalplan, CRM-Anbindung und Echtzeit-Verkaufsdaten.",
    ergebnis: "Ticketing-Gebühren um 75% reduziert, volle Kontrolle über Kundendaten.",
    stack: ["Next.js", "Stripe", "PostgreSQL", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Gebühren", value: "-75%" }, { label: "Events", value: "40+" }, { label: "Tickets", value: "8k+" }, { label: "Lieferzeit", value: "10 Wo." }],
  },
  {
    slug: "handwerk-digital",
    client: "Handwerk Digital e.V.",
    title: "Branchenportal",
    description: "Digitales Branchenverzeichnis mit Betriebsprofilen, Bewertungen und Auftragsvermittlung.",
    tags: ["Plattform", "Webdesign", "SEO", "CMS"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Handwerk / Verband",
    aufgabe: "Kein zentrales Portal für die Mitgliedsbetriebe, keine digitale Auftragsvermittlung.",
    loesung: "Branchenportal mit Betriebsprofilen, Bewertungssystem und Auftragsmatching-Algorithmus.",
    ergebnis: "200+ registrierte Betriebe, 500+ vermittelte Aufträge im ersten Jahr.",
    stack: ["Next.js", "Supabase", "Sanity CMS", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Betriebe", value: "200+" }, { label: "Aufträge", value: "500+" }, { label: "Nutzer", value: "5k+" }, { label: "Lieferzeit", value: "14 Wo." }],
  },
  {
    slug: "mode-atelier-sophie",
    client: "Atelier Sophie",
    title: "Fashion E-Commerce",
    description: "Designermode-Shop mit Lookbook, Size-Guide und personalisierten Empfehlungen.",
    tags: ["E-Commerce", "Webdesign", "Headless", "UX"],
    image: "https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Fashion / Retail",
    aufgabe: "Etsy-Shop ohne eigene Brand-Experience. Keine Kontrolle über Kundenbeziehung.",
    loesung: "Eigener Headless-Shop mit Lookbook, Size-Guide, Wishlist und personalisierten Empfehlungen.",
    ergebnis: "AOV +30%, Retourenquote -15% dank besserem Size-Guide.",
    stack: ["Next.js", "Shopify Headless", "Sanity CMS", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "AOV", value: "+30%" }, { label: "Retouren", value: "-15%" }, { label: "Lighthouse", value: "96" }, { label: "Lieferzeit", value: "7 Wo." }],
  },
  {
    slug: "solar-sachsen",
    client: "Solar Sachsen GmbH",
    title: "Solarrechner & Website",
    description: "Website mit interaktivem Solarrechner, Lead-Generierung und automatisierter Angebotserstellung.",
    tags: ["Webdesign", "Web-App", "Lead-Gen", "API"],
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Energie / Solar",
    aufgabe: "Keine digitale Lead-Generierung, alle Anfragen kamen über Mundpropaganda.",
    loesung: "Website mit interaktivem Solarrechner basierend auf Dachfläche, Ausrichtung und Verbrauch.",
    ergebnis: "200+ qualifizierte Leads pro Monat, automatisierte Angebotserstellung in unter 5 Minuten.",
    stack: ["Next.js", "Sanity CMS", "Node.js API", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1509391366360-2e959784a276?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Leads/Monat", value: "200+" }, { label: "Angebot in", value: "<5 Min" }, { label: "Lighthouse", value: "95" }, { label: "Lieferzeit", value: "6 Wo." }],
  },
  {
    slug: "plauderbot-ai",
    client: "Plauderbot",
    title: "KI-Chatbot Plattform",
    description: "Eigenes Produkt: KI-gestützter Chatbot für Websites mit natürlichem Gesprächsfluss.",
    tags: ["KI", "SaaS", "Produkt", "API"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "SaaS / KI",
    aufgabe: "Eigenes Produkt — KI-Chatbots für Websites waren entweder zu teuer oder zu schlecht.",
    loesung: "Plauderbot: KI-Chatbot der auf Unternehmens-Daten trainiert wird und natürlich kommuniziert.",
    ergebnis: "50+ zahlende Kunden, durchschnittlich 30% weniger Support-Tickets bei Kunden.",
    stack: ["Next.js", "OpenAI API", "Supabase", "TypeScript"],
    images: ["https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Kunden", value: "50+" }, { label: "Support", value: "-30%" }, { label: "Antwortzeit", value: "<2s" }, { label: "Uptime", value: "99.9%" }],
  },
  {
    slug: "lumera-ai",
    client: "Lumera.ai",
    title: "KI-Analytics Platform",
    description: "Eigenes Produkt: KI-gestützte Business-Analytics-Plattform für datengetriebene Entscheidungen.",
    tags: ["KI", "SaaS", "Dashboard", "Analytics"],
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "SaaS / KI",
    aufgabe: "Eigenes Produkt — Business Intelligence war für KMU zu komplex und zu teuer.",
    loesung: "Lumera.ai: KI-gestützte Analytics die Geschäftsdaten automatisch analysiert und Handlungsempfehlungen gibt.",
    ergebnis: "Beta mit 20+ Unternehmen, durchschnittlich 25% bessere Entscheidungsgeschwindigkeit.",
    stack: ["Next.js", "Python", "OpenAI", "PostgreSQL", "Tailwind CSS"],
    images: ["https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Beta-Kunden", value: "20+" }, { label: "Schnellere Entsch.", value: "+25%" }, { label: "Datenquellen", value: "15+" }, { label: "Status", value: "Beta" }],
  },
];
