export interface Project {
  slug: string;
  client: string;
  title: string;
  description: string;
  tags: string[];
  image: string;
  year: string;
  branche: string;
  aufgabe: string;
  loesung: string;
  ergebnis: string;
  stack: string[];
  testimonial?: {
    text: string;
    name: string;
    role: string;
  };
  liveUrl?: string;
  images: string[];
  stats: { label: string; value: string }[];
}

export const PROJECTS: Project[] = [
  {
    slug: "laasen-perle",
    client: "Bergpension Laasen Perle",
    title: "Bergpension Laasen Perle",
    description: "Kompletter Website-Relaunch für eine Bergpension in der Sächsischen Schweiz. Next.js, Sanity CMS, Buchungssystem und Lighthouse 95+.",
    tags: ["Webdesign", "Next.js", "SEO", "Buchungssystem"],
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gastgewerbe / Tourismus",
    aufgabe: "Die bestehende Website war veraltet und nicht mobiloptimiert. Gäste konnten keine Zimmer direkt buchen und die Sichtbarkeit bei Google war minimal.",
    loesung: "Kompletter Relaunch mit Next.js 15 und Tailwind CSS. Zimmer-Galerie, Preisübersicht, integriertes Buchungssystem und Lighthouse Performance Monitoring.",
    ergebnis: "Lighthouse Score 95+, Ladezeit unter 1 Sekunde, deutlich mehr organische Anfragen seit Launch.",
    stack: ["Next.js 15", "React", "Tailwind CSS", "Lucide Icons", "Lighthouse CI", "Vercel"],
    liveUrl: "https://www.laasenperle.de",
    images: [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Lighthouse", value: "95+" }, { label: "Ladezeit", value: "<1s" }, { label: "Standort", value: "Rathen" }, { label: "Stack", value: "Next.js 15" }],
  },
  {
    slug: "lucram-media",
    client: "Lucram Media",
    title: "Corporate Website",
    description: "Premium-Website für Lucram Media mit scroll-basiertem Storytelling, Video-Hintergründen und Custom-Animationen. Projekte mit Siemens, Intel, Gönrgy.",
    tags: ["Branding", "Webdesign", "Animationen", "Video"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Digital Media / Video Production",
    aufgabe: "Lucram Media brauchte eine Website, die ihre Arbeit mit Marken wie Siemens, Intel und Gönrgy auf Premium-Niveau präsentiert — mit Scroll-Storytelling und Video-Integration.",
    loesung: "Custom Next.js Website mit eigenen Scroll-Komponenten (StickySection, TiltCard, ZoomImage), YouTube-Video-Hintergründen, Testimonial-Karussell und Case Study Detail-Seiten für jedes Projekt.",
    ergebnis: "Hochwertige Darstellung der Referenzen (Siemens SIEYA, Intel IEM, HAPS Kinofilm, Gönrgy, Erkenne Den). Scroll-Storytelling mit immersivem Erlebnis.",
    stack: ["Next.js 16", "React", "Tailwind CSS 4", "Custom Scroll Animations", "YouTube API"],
    images: [
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1740&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1740&auto=format&fit=crop",
    ],
    stats: [{ label: "Case Studies", value: "5" }, { label: "Kunden", value: "Siemens, Intel" }, { label: "Reach", value: "35 Mio." }, { label: "Stack", value: "Next.js 16" }],
  },
  {
    slug: "kajamed",
    client: "Kajamed",
    title: "Medizintechnik-Portal",
    description: "Website für Kajamed — Orthopädietechnik, Rehatechnik und Sanitätsfachhandel mit Filialsystem in Zwickau, Chemnitz und Leubnitz.",
    tags: ["Webdesign", "CMS", "Medizintechnik", "Multi-Standort"],
    image: "https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Medizintechnik / Gesundheit",
    aufgabe: "Kajamed brauchte eine professionelle Online-Präsenz, die alle Standorte und Leistungsbereiche (Orthopädie, Reha, Kinderorthopädie, Sanitätshaus) übersichtlich darstellt.",
    loesung: "Responsive Website mit Multi-Standort-System, Leistungsportfolio-Darstellung, Stellenangeboten und Kontaktmöglichkeiten pro Filiale.",
    ergebnis: "Professionelle Darstellung aller 4 Standorte, übersichtliche Service-Navigation, verbesserte lokale Sichtbarkeit.",
    stack: ["Next.js 15", "React 18", "Tailwind CSS 3", "Lucide Icons"],
    liveUrl: "https://www.kajamed.de",
    images: ["https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standorte", value: "4" }, { label: "Services", value: "5+" }, { label: "Region", value: "Sachsen" }, { label: "Live", value: "kajamed.de" }],
  },
  {
    slug: "sv-raedisch",
    client: "Sachverständigenbüro Rädisch",
    title: "Immobiliengutachter",
    description: "Professionelle Website für einen Immobiliensachverständigen in Sachsen — Verkehrswertgutachten, Marktwertgutachten und Immobilienberatung.",
    tags: ["Webdesign", "SEO", "Lokal SEO", "Gutachter"],
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Immobilien / Sachverständiger",
    aufgabe: "Der Sachverständige brauchte eine seriöse Online-Präsenz mit klarer Leistungsdarstellung und lokaler SEO für ganz Sachsen.",
    loesung: "Statische Website mit Alpine.js und Tailwind CSS. Professionelles Schema-Markup, Preisübersicht, Expertenvorstellung und Kontaktmöglichkeiten.",
    ergebnis: "Sichtbarkeit für lokale Suchbegriffe in Dresden, Leipzig, Chemnitz und Umgebung. Seriöser, vertrauensbildender Webauftritt.",
    stack: ["HTML", "Alpine.js", "Tailwind CSS 3"],
    liveUrl: "https://www.sv-raedisch.de",
    images: ["https://images.unsplash.com/photo-1560518883-ce09059eeffa?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Region", value: "Sachsen" }, { label: "Städte", value: "6+" }, { label: "Live", value: "sv-raedisch.de" }, { label: "SEO", value: "Lokal" }],
  },
  {
    slug: "44studio",
    client: "44Studio",
    title: "Creator Management Agency",
    description: "Website für 44Studio — strategisches Creator Management, Content Production und Social Media Strategieberatung.",
    tags: ["Branding", "Webdesign", "Creator Economy", "Animationen"],
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Creator Management / Social Media",
    aufgabe: "44Studio brauchte eine Agentur-Website, die ihr Creator-Portfolio und ihre Brand-Partnerships auf höchstem Niveau präsentiert.",
    loesung: "Next.js Website mit Framer Motion Animationen, Creator-Showcase, Partnership-Marquee und Portfolio-Darstellung.",
    ergebnis: "Professionelle Darstellung des Creator-Portfolios mit immersiven Animationen und moderner Ästhetik.",
    stack: ["Next.js 16", "React", "Framer Motion", "Phosphor Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Animationen", value: "Framer" }, { label: "Stack", value: "Next.js 16" }, { label: "Branche", value: "Creator" }, { label: "Design", value: "Premium" }],
  },
  {
    slug: "memora",
    client: "Memora",
    title: "Influencer Marketing Agency",
    description: "Website für Memora — #1 Partner für Influencer Marketing mit exklusiven und nicht-exklusiven Creator-Kooperationen in Berlin und München.",
    tags: ["Branding", "Webdesign", "Influencer", "Scroll-Galerie"],
    image: "https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Influencer Marketing",
    aufgabe: "Memora brauchte eine Plattform, die ihre Creator-Kooperationen und Brand-Partnerschaften überzeugend darstellt — mit Standorten in Berlin und München.",
    loesung: "Next.js Website mit horizontaler Scroll-Galerie, Creator-Showcase, Partnership-Präsentationen und immersivem Design.",
    ergebnis: "Überzeugende Darstellung des Creator-Netzwerks mit interaktiver Galerie und modernem Agentur-Auftritt.",
    stack: ["Next.js 16", "React", "Phosphor Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1557838923-2985c318be48?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standorte", value: "Berlin, München" }, { label: "Typ", value: "Agentur" }, { label: "Stack", value: "Next.js 16" }, { label: "Feature", value: "Scroll-Galerie" }],
  },
  {
    slug: "vision-media",
    client: "Vision Media",
    title: "Videoproduktion Website",
    description: "Portfolio-Website für Vision Media — Cinematic Video Content, High-End Photography und Social Media Content Production.",
    tags: ["Webdesign", "Portfolio", "Video", "Kreativagentur"],
    image: "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Videoproduktion / Kreativagentur",
    aufgabe: "Vision Media brauchte eine Portfolio-Website, die ihre cinematischen Produktionen und fotografischen Arbeiten wirkungsvoll in Szene setzt.",
    loesung: "Visuelle Portfolio-Website mit Video-Reels, Manifesto-Sektion, Statistiken und immersiver Bildsprache.",
    ergebnis: "Kraftvolle Darstellung des kreativen Portfolios mit Video-Integration und professioneller Positionierung.",
    stack: ["Next.js 16", "React", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Portfolio" }, { label: "Content", value: "Video + Foto" }, { label: "Stack", value: "Next.js 16" }, { label: "Design", value: "Cinematic" }],
  },
  {
    slug: "glasbison",
    client: "Glass Bison",
    title: "Künstler-Management",
    description: "Website für Glass Bison — Künstler-Management mit strategischem Ansatz und kreativer Vision. Portfolio-Showcase und Artist-Darstellung.",
    tags: ["Webdesign", "Branding", "Musik", "Portfolio"],
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Musik & Entertainment",
    aufgabe: "Glass Bison brauchte eine Website, die ihr Künstler-Management professionell präsentiert — mit strategischem und kreativem Ansatz.",
    loesung: "Moderne Portfolio-Website mit Framer Motion Animationen, Artist-Showcase und Management-Darstellung.",
    ergebnis: "Professioneller Online-Auftritt für das Künstler-Management mit immersivem Design und klarer Positionierung.",
    stack: ["Next.js 16", "React", "Framer Motion", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Musik" }, { label: "Typ", value: "Management" }, { label: "Stack", value: "Next.js 16" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "vietnam-nam",
    client: "Vietnam Nam",
    title: "Restaurant Website",
    description: "Zweisprachige Website für ein vietnamesisches Restaurant in Chemnitz — Speisekarte, Reservierung und Kontakt auf Deutsch und Vietnamesisch.",
    tags: ["Webdesign", "Gastronomie", "Zweisprachig", "Reservierung"],
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Gastronomie",
    aufgabe: "Vietnam Nam brauchte eine ansprechende Website mit Speisekarte, Online-Reservierung und zweisprachiger Darstellung (Deutsch/Vietnamesisch).",
    loesung: "Next.js Website mit Nodemailer für Kontaktformulare, zweisprachigem Interface, Speisekarten-Integration und Öffnungszeiten.",
    ergebnis: "Professioneller Restaurant-Auftritt mit funktionaler Reservierung und zweisprachiger Bedienung.",
    stack: ["Next.js 16", "React", "Nodemailer", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Sprachen", value: "DE + VN" }, { label: "Standort", value: "Chemnitz" }, { label: "Features", value: "Reservierung" }, { label: "E-Mail", value: "Nodemailer" }],
  },
  {
    slug: "salty-beach",
    client: "Salty Beach",
    title: "Luxury Salt Lounge",
    description: "Premium-Website für eine Design-Salzlounge mit Halotherapie — zweisprachig (Englisch/Arabisch) mit Smooth-Scroll-Animationen.",
    tags: ["Webdesign", "Luxury", "Wellness", "Zweisprachig"],
    image: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Wellness / Luxury",
    aufgabe: "Salty Beach brauchte eine Premium-Website, die das exklusive Salzlounge-Erlebnis visuell einfängt — zweisprachig für ein internationales Publikum.",
    loesung: "Luxury-Website mit Lenis Smooth Scrolling, Framer Motion Animationen, zweisprachigem Content (EN/AR) und Gallery-Sektionen.",
    ergebnis: "Hochwertiger, immersiver Online-Auftritt der das Premium-Erlebnis der Salzlounge digital transportiert.",
    stack: ["Next.js 16", "React", "Framer Motion", "Lenis", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Sprachen", value: "EN + AR" }, { label: "Scrolling", value: "Lenis" }, { label: "Design", value: "Luxury" }, { label: "Animationen", value: "Framer" }],
  },
  {
    slug: "regalflaechendesign",
    client: "Regalflächendesign",
    title: "Laden- und Messebau",
    description: "Website für Regalflächendesign — Montagen im Laden- und Messebau, Regalflächenbau und Regalprüfung in Chemnitz.",
    tags: ["Webdesign", "Handwerk", "Vorher/Nachher", "Kontakt"],
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop",
    year: "2024",
    branche: "Laden- und Messebau",
    aufgabe: "Regalflächendesign brauchte eine professionelle Website, die ihre Montage-Leistungen im Laden- und Messebau überzeugend darstellt.",
    loesung: "Responsive Website mit Vorher/Nachher-Slidern für Referenzprojekte, Leistungsübersicht, Stellenangeboten und Kontaktformular.",
    ergebnis: "Professionelle Online-Präsenz mit visuellen Projektbeispielen und direkter Kontaktmöglichkeit.",
    stack: ["Next.js 15", "React", "Clsx", "Lucide Icons", "Tailwind CSS 3"],
    images: ["https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Standort", value: "Chemnitz" }, { label: "Feature", value: "Vorher/Nachher" }, { label: "Tel.", value: "0371 234794 10" }, { label: "Stack", value: "Next.js 15" }],
  },
  {
    slug: "in-tec",
    client: "In-Tec",
    title: "Bauunternehmen Website",
    description: "Moderne Unternehmenswebsite für In-Tec — Bauunternehmen mit Vorher/Nachher-Slidern, Social Proof und Leistungsdarstellung.",
    tags: ["Webdesign", "Bau", "Vorher/Nachher", "SEO"],
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Bau / Handwerk",
    aufgabe: "In-Tec brauchte eine moderne Website, die ihr Leistungsspektrum im Bauwesen professionell darstellt und Vertrauen schafft.",
    loesung: "Next.js Website mit Vorher/Nachher-Slider für Bauprojekte, Service-Sektionen, Social Proof Elementen und Kontaktformular.",
    ergebnis: "Überzeugende Darstellung der Bauleistungen mit visuellen Projektreferenzen.",
    stack: ["Next.js 16", "React", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Bau" }, { label: "Feature", value: "Slider" }, { label: "Stack", value: "Next.js 16" }, { label: "Design", value: "Modern" }],
  },
  {
    slug: "trendbau",
    client: "Trendbau",
    title: "Bauunternehmen Website",
    description: "Website für Trendbau — Bauunternehmen mit Projektgalerie, Vorher/Nachher-Vergleichen und Leistungsübersicht.",
    tags: ["Webdesign", "Bau", "Portfolio", "Kontakt"],
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Bau / Handwerk",
    aufgabe: "Trendbau brauchte eine professionelle Website, die ihre Bauprojekte und Leistungen überzeugend präsentiert.",
    loesung: "Moderne Website mit Geist UI Typography, Vorher/Nachher-Slidern, Service-Showcase und Kontaktformularen.",
    ergebnis: "Professioneller Webauftritt mit visueller Projektdarstellung und klarer Leistungskommunikation.",
    stack: ["Next.js 16", "React", "Geist UI", "Lucide Icons", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Bau" }, { label: "Font", value: "Geist UI" }, { label: "Stack", value: "Next.js 16" }, { label: "Feature", value: "Slider" }],
  },
  {
    slug: "bedag",
    client: "BeDaG",
    title: "Handwerksbetrieb Website",
    description: "Website für BeDaG — Handwerksbetrieb mit Service-Karten, Kundenstimmen und Blog-Sektion.",
    tags: ["Webdesign", "Handwerk", "Blog", "Testimonials"],
    image: "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Handwerk / Renovation",
    aufgabe: "BeDaG brauchte eine moderne Website mit Leistungsdarstellung, Kundenstimmen und einem Blog für Expertise-Positionierung.",
    loesung: "Next.js Website mit Framer Motion Animationen, Service-Karten, Testimonial-Sektion und integriertem Blog.",
    ergebnis: "Moderner Webauftritt mit Kundenstimmen, Blog-Content und klarer Service-Darstellung.",
    stack: ["Next.js 16", "React", "Framer Motion", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1621905252507-b35492cc74b4?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Branche", value: "Handwerk" }, { label: "Feature", value: "Blog" }, { label: "Animationen", value: "Framer" }, { label: "Stack", value: "Next.js 16" }],
  },
  {
    slug: "krell-immobilien",
    client: "Krell",
    title: "Immobilienentwicklung",
    description: "Website für Krell — Immobilienentwicklung mit interaktiver Leaflet-Karte, Objektgalerie und Standort-Visualisierung.",
    tags: ["Webdesign", "Immobilien", "Karten", "Interaktiv"],
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Immobilien / Projektentwicklung",
    aufgabe: "Krell brauchte eine Website, die ihre Immobilienprojekte mit interaktiven Karten und Galerien wirkungsvoll präsentiert.",
    loesung: "Next.js Website mit Leaflet-Kartenintegration für Standort-Visualisierung, Projektgalerie und Property-Showcase.",
    ergebnis: "Interaktive Immobilien-Darstellung mit Kartennavigation und hochwertigem Projekt-Showcase.",
    stack: ["Next.js 16", "React", "Leaflet", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Feature", value: "Leaflet Maps" }, { label: "Typ", value: "Immobilien" }, { label: "Stack", value: "Next.js 16" }, { label: "Interaktiv", value: "Karte" }],
  },
  {
    slug: "gegenschlag24",
    client: "Gegenschlag 24",
    title: "Fußball-Team Website",
    description: "Website für GS24 — Fußball-Team mit Spielplan, Kader-Übersicht, News-Sektion und Sponsoren-Darstellung.",
    tags: ["Webdesign", "Sport", "Team", "News"],
    image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Sport / Fußball",
    aufgabe: "Das Fußball-Team brauchte eine Website mit Spielplan, Kader, News und Sponsoren-Darstellung.",
    loesung: "Moderne Team-Website mit Spielplan-System, Kader-Übersicht, News-Sektion und Sponsor-Showcase.",
    ergebnis: "Zentrale Anlaufstelle für Fans und Sponsoren mit allen Team-Informationen.",
    stack: ["Next.js 16", "React", "Geist UI", "Tailwind CSS 4"],
    images: ["https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Team-Website" }, { label: "Features", value: "Spielplan" }, { label: "Stack", value: "Next.js 16" }, { label: "Content", value: "News" }],
  },
  {
    slug: "plauderbot",
    client: "Plauderbot",
    title: "KI-Chatbot Produkt",
    description: "Landing Page für Plauderbot — eigenes Produkt: KI-gestützter Chatbot für Websites mit Feature-Highlights und Produkt-Showcase.",
    tags: ["KI", "SaaS", "Produkt", "Landing Page"],
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Software / KI",
    aufgabe: "Plauderbot ist unser eigenes Produkt — ein KI-Chatbot für Websites. Die Landing Page soll Features, Vorteile und Preise überzeugend darstellen.",
    loesung: "Produkt-Landing-Page mit Feature-Highlights, Preis-Darstellung und klarem Call-to-Action.",
    ergebnis: "Überzeugende Produktseite, die Plauderbot als professionelle KI-Lösung positioniert.",
    stack: ["Next.js 15", "React 18", "Tailwind CSS 3", "Lucide Icons"],
    images: ["https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Typ", value: "Eigenes Produkt" }, { label: "Technologie", value: "KI/AI" }, { label: "Stack", value: "Next.js 15" }, { label: "Status", value: "Live" }],
  },
  {
    slug: "defuse-digital",
    client: "defuse. digital",
    title: "Eigene Agentur-Website",
    description: "Unsere eigene Website — mit scroll-basiertem Storytelling, 22+ Case Studies, Projekt-Konfigurator und vollständiger SEO-Infrastruktur.",
    tags: ["Webdesign", "SEO", "Animationen", "Konfigurator"],
    image: "https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop",
    year: "2025",
    branche: "Digitalagentur",
    aufgabe: "Unsere eigene Website sollte zeigen, was wir können — Premium-Design, SEO-Infrastruktur, Custom-Komponenten und einen vollständigen Projekt-Konfigurator.",
    loesung: "Next.js 16 Website mit Custom Scroll-Komponenten (StickySection, TiltCard, Reveal, CountUp), JSON-LD, programmatischer Sitemap, 9-Schritte Projekt-Konfigurator.",
    ergebnis: "Eat-your-own-dogfood: Die Website demonstriert live, was wir für unsere Kunden bauen.",
    stack: ["Next.js 16", "React", "Tailwind CSS 4", "Lucide Icons", "TypeScript", "Vercel"],
    images: ["https://images.unsplash.com/photo-1551434678-e076c223a692?q=80&w=1740&auto=format&fit=crop"],
    stats: [{ label: "Projekte", value: "22+" }, { label: "Konfigurator", value: "9 Steps" }, { label: "SEO", value: "JSON-LD" }, { label: "Stack", value: "Next.js 16" }],
  },
];
